#ifndef SOLUCIONARIO_TICADEMIA_FUNCIONES_AUXILIARES_H
#define SOLUCIONARIO_TICADEMIA_FUNCIONES_AUXILIARES_H

int ingreso_valido(int valor, int minimo, int maximo);

#endif //SOLUCIONARIO_TICADEMIA_FUNCIONES_AUXILIARES_H
